### ISSUE TITLE
Eventuele Fix voor GitHub API Styling

### ISSUE THREAD

**Issue by moonlightlizaa** [EmonaSantiago/PORTFOLIO#22]
De styling voor de Github API kan ook in `app.html` geplaatst worden als het niet werkt 💗

**Comment by EmonaSantiago** [comment]
**Issue styling github API niet te pakken**

De integratie van de GitHub API verliep succesvol, maar ik had moeite met de implementatie van de styling in de code. Om dit op te lossen, heb ik hulp gevraagd aan mijn oud-klasgenoten Marco en Eliza. Zij hebben samen met mij naar de code gekeken. Na enkele testrondes is het uiteindelijk gelukt om de styling correct toe te passen door deze via de app.html aan te geven.

Hiervoor hadden we een online teams call
<img width="400" alt="Schermafbeelding 2024-08-22 om 15 12 20" src="https://github.com/user-attachments/assets/1e231718-5a56-4a72-9047-e57fc2122457">
